# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enernite_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnerniteUploaderDockWidgetBase(object):
    def setupUi(self, EnerniteUploaderDockWidgetBase):
        EnerniteUploaderDockWidgetBase.setObjectName("EnerniteUploaderDockWidgetBase")
        EnerniteUploaderDockWidgetBase.resize(232, 220)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.usernameLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.usernameField = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.usernameField.setObjectName("usernameField")
        self.gridLayout.addWidget(self.usernameField, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordField = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.gridLayout.addWidget(self.passwordField, 1, 1, 1, 1)
        self.signInButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.signInButton.setObjectName("signInButton")
        self.gridLayout.addWidget(self.signInButton, 2, 0, 1, 2)
        self.uploadToProjectButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.uploadToProjectButton.setEnabled(False)
        self.uploadToProjectButton.setObjectName("uploadToProjectButton")
        self.gridLayout.addWidget(self.uploadToProjectButton, 3, 0, 1, 2)
        self.loggedInTextLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.loggedInTextLabel.setVisible(False)
        self.loggedInTextLabel.setObjectName("loggedInTextLabel")
        self.gridLayout.addWidget(self.loggedInTextLabel, 4, 0, 1, 1)
        self.loaderProgressBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.loaderProgressBar.setVisible(False)
        self.loaderProgressBar.setObjectName("loaderProgressBar")
        self.gridLayout.addWidget(self.loaderProgressBar, 5, 0, 1, 1)
        self.projectUploadedTextLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.projectUploadedTextLabel.setVisible(False)
        self.projectUploadedTextLabel.setObjectName("projectUploadedTextLabel")
        self.gridLayout.addWidget(self.projectUploadedTextLabel, 6, 0, 1, 1)
        EnerniteUploaderDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(EnerniteUploaderDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(EnerniteUploaderDockWidgetBase)

    def retranslateUi(self, EnerniteUploaderDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        EnerniteUploaderDockWidgetBase.setWindowTitle(_translate("EnerniteUploaderDockWidgetBase", "Enernite Uploader"))
        self.usernameLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Username:"))
        self.passwordLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Password:"))
        self.signInButton.setText(_translate("EnerniteUploaderDockWidgetBase", "Sign In"))
        self.uploadToProjectButton.setText(_translate("EnerniteUploaderDockWidgetBase", "Upload to Project"))
        self.loggedInTextLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Successfully logged in as: {Username}"))
        self.projectUploadedTextLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Project uploaded and available at: {LINK}"))
