# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enernite_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnerniteUploaderDockWidgetBase(object):
    def setupUi(self, EnerniteUploaderDockWidgetBase):
        EnerniteUploaderDockWidgetBase.setObjectName("EnerniteUploaderDockWidgetBase")
        EnerniteUploaderDockWidgetBase.resize(232, 300)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bannerLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.bannerLabel.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.bannerLabel.setFont(font)
        self.bannerLabel.setObjectName("bannerLabel")
        self.verticalLayout.addWidget(self.bannerLabel)
        self.usernameLoggedIn = QtWidgets.QLabel(self.dockWidgetContents)
        self.usernameLoggedIn.setObjectName("usernameLoggedIn")
        self.verticalLayout.addWidget(self.usernameLoggedIn)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usernameLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 0, 0, 1, 1)
        self.usernameField = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.usernameField.setObjectName("usernameField")
        self.gridLayout.addWidget(self.usernameField, 0, 1, 1, 1)
        self.passwordLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.passwordLabel.setObjectName("passwordLabel")
        self.gridLayout.addWidget(self.passwordLabel, 1, 0, 1, 1)
        self.passwordField = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.gridLayout.addWidget(self.passwordField, 1, 1, 1, 1)
        self.signInButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.signInButton.setObjectName("signInButton")
        self.gridLayout.addWidget(self.signInButton, 2, 0, 1, 2)
        self.projectNameLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.gridLayout.addWidget(self.projectNameLabel, 3, 0, 1, 1)
        self.projectNameField = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.projectNameField.setObjectName("projectNameField")
        self.gridLayout.addWidget(self.projectNameField, 3, 1, 1, 1)
        self.uploadToProjectButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.uploadToProjectButton.setEnabled(False)
        self.uploadToProjectButton.setObjectName("uploadToProjectButton")
        self.gridLayout.addWidget(self.uploadToProjectButton, 4, 0, 1, 2)
        self.loggedInTextLabel = QtWidgets.QLabel(self.dockWidgetContents)
        self.loggedInTextLabel.setVisible(False)
        self.loggedInTextLabel.setObjectName("loggedInTextLabel")
        self.gridLayout.addWidget(self.loggedInTextLabel, 5, 0, 1, 2)
        self.loaderProgressBar = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.loaderProgressBar.setHidden(False)
        self.loaderProgressBar.setMinimum(0)
        self.loaderProgressBar.setMaximum(100)
        self.loaderProgressBar.setProperty("value", 50)
        self.loaderProgressBar.setObjectName("loaderProgressBar")
        self.gridLayout.addWidget(self.loaderProgressBar, 6, 0, 1, 2)
        self.projectUploadedButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.projectUploadedButton.setEnabled(False)
        self.projectUploadedButton.setObjectName("projectUploadedButton")
        self.gridLayout.addWidget(self.projectUploadedButton, 7, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        EnerniteUploaderDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(EnerniteUploaderDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(EnerniteUploaderDockWidgetBase)

    def retranslateUi(self, EnerniteUploaderDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        EnerniteUploaderDockWidgetBase.setWindowTitle(_translate("EnerniteUploaderDockWidgetBase", "Enernite Uploader"))
        self.bannerLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Enernite Uploader"))
        self.usernameLoggedIn.setText(_translate("EnerniteUploaderDockWidgetBase", "Logged in as {USER}"))
        self.usernameLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Username:"))
        self.passwordLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Password:"))
        self.signInButton.setText(_translate("EnerniteUploaderDockWidgetBase", "Sign In"))
        self.projectNameLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Project Name:"))
        self.uploadToProjectButton.setText(_translate("EnerniteUploaderDockWidgetBase", "Create project and upload data"))
        self.loggedInTextLabel.setText(_translate("EnerniteUploaderDockWidgetBase", "Logged in as: {Username}"))
        self.projectUploadedButton.setText(_translate("EnerniteUploaderDockWidgetBase", "Success! Click here to go to project"))
